# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
    

      
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env


networks:
  default: development
  development:
    cmd_settings:
      mnemonic: brownie
      default_balance: 100000000000000000000
      unlock: <ACCOUNT ADDRESS HERE> # optionally add saved brownie account to Ganache
      # (requires explicit transfer of eth to accounts[-1]) 

    update_interval: 60
    verify: False

  rinkeby:
    verify: False
    weth_token: '0xc778417E063141139Fce010982780140Aa0cD5Ab'
  
  kovan:

    verify: False
    update_interval: 60


wallets:
  from_key: ${PRIVATE_KEY}


# enable output of development artifacts to load with react
dev_deployment_artifacts: true
